# Generated by Django 6.0.6 on 2026-08-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0009_table_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='compressed_image',
            field=models.ImageField(default='menuitem-placeholder.png', upload_to='compressed_images_menupage/'),
        ),
    ]
