# Generated by Django 6.1 on 2026-09-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0012_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='compressed_image',
            field=models.ImageField(default='LittleLemonFiles/CompressedImages/menuitem-placeholder.png', upload_to='LittleLemonFiles/CompressedImages/'),
        ),
    ]
